title: Frontanería
email: frontaneros@gmail.com
description: "Página web de Frontaneros/as"
baseurl: ""
url: "https://frontaneros.github.io"
Github: https://github.com/Frontaneros

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap

theme: jekyll-theme-cayman